import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.enums import TA_CENTER,TA_JUSTIFY,TA_LEFT
from reportlab.lib import colors

def create_student_report_pdf(teachers_name:str,course_name:str,course_code:str,class_name:str,section:str,df_above80:pd.DataFrame,df_below40:pd.DataFrame,df_70to80:pd.DataFrame) -> None: 
  
  # Empty page
  doc = SimpleDocTemplate("report.pdf",pageSize=A4)

  # Font styles margin etc
  styles = getSampleStyleSheet()

  # PDF content
  story = []

  # Styles for pdf
  styles.add(ParagraphStyle(
    name="Base",
    fontName="Times-Roman",
    fontSize=12,
    leading=18,  # line height (1.5 * 12)
    alignment=TA_JUSTIFY
  ))
 
  styles.add(ParagraphStyle(
    name="heading",
    parent=styles["Base"],
    fontName="Times-Bold",
    fontSize=14,
    alignment=TA_CENTER
  ))

  styles.add(ParagraphStyle(
    name="subheading",
    parent=styles["Base"],
    fontName="Times-Bold",
    fontSize=12,
    alignment=TA_JUSTIFY
  ))

  # Content,creation
  story.append(Paragraph(("Student performace report").upper(),styles["heading"]))
  story.append(Spacer(0,20))

  story.append(Paragraph(f"This is a sample report generated by {teachers_name} for subject {course_name} having course code {course_code}. The report is a summary of performace of class {class_name} section {section}.",styles["Base"]))
  story.append(Spacer(0,20))

  story.append(Paragraph("1. Student scoring above 80%",styles["subheading"]))
  story.append(Spacer(0,20))

  table_data = [["RegNo","Name","Score"],["1","ABC","87%"],["2","DEF","87%"],["3","GHI","87%"],["4","JKL","87%"],["5","XYZ","87%"]]
  
  table = create_table(table_data=table_data)
  story.append(table)
  story.append(Spacer(0,20))

  story.append(Paragraph(f"This is some summary about the table above. This is a sample report generated by {teachers_name} for subject {course_name} having course code {course_code}. The report is a summary of performace of class {class_name} section {section}.",styles["Base"]))
  story.append(Spacer(0,20))
  
  story.append(Paragraph("2. Student scoring between 70%-80%",styles["subheading"]))
  story.append(Spacer(0,20))

  table_data = [["RegNo","Name","Score"],["1","ABC","87%"],["2","DEF","87%"],["3","GHI","87%"],["4","JKL","87%"],["5","XYZ","87%"]]
  
  table = create_table(table_data=table_data)
  story.append(table)
  story.append(Spacer(0,20))

  story.append(Paragraph(f"This is some summary about the table above. This is a sample report generated by {teachers_name} for subject {course_name} having course code {course_code}. The report is a summary of performace of class {class_name} section {section}.",styles["Base"]))
  story.append(PageBreak())
  
  story.append(Paragraph("3. Student scoring below 40%",styles["subheading"]))
  story.append(Spacer(0,20))

  table_data = [["RegNo","Name","Score"],["1","ABC","87%"],["2","DEF","87%"],["3","GHI","87%"],["4","JKL","87%"],["5","XYZ","87%"]]
  
  table = create_table(table_data=table_data)
  story.append(table)
  story.append(Spacer(0,20))

  story.append(Paragraph(f"This is some summary about the table above. This is a sample report generated by {teachers_name} for subject {course_name} having course code {course_code}. The report is a summary of performace of class {class_name} section {section}.",styles["Base"]))
  story.append(Spacer(0,20))

  # PDF building
  doc.build(story)


def create_table(table_data:list)->Table:
  table = Table(table_data,colWidths=[150,150,150])
  table.setStyle([
    ("FONTNAME", (0,0), (-1,0), "Times-Bold"),
    ("FONTNAME", (0,1), (-1,-1), "Times-Roman"),
    ("FONTSIZE", (0,0), (-1,-1), 10),
    ("TEXTCOLOR", (0,0), (0,-1), colors.black),
    ("ALIGN", (0,0), (-1,-1), "CENTER"),
    ('ROWHEIGHT', (0, 0), (-1, -1), 25),
    ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ("INNERGRID", (0,0), (-1,-1), 1, colors.black),
    ("BOX", (0,0), (-1,-1), 1, colors.black),
  ])
  return table


create_student_report_pdf(teachers_name="Dr.Abc",course_code="CSE302A",course_name="C Programming",section="B08A",class_name="Btech CSE",df_70to80=pd.DataFrame([]),df_above80=pd.DataFrame([]),df_below40=pd.DataFrame([]))